# Generated by Django 5.1.1 on 2024-09-24 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
        migrations.AlterUniqueTogether(
            name='ratemovieuser',
            unique_together={('user', 'movie')},
        ),
        migrations.AddField(
            model_name='ratemovieuser',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ratemovieuser',
            name='rate',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
